### ISSUE TITLE
oommfc.test() tornado conda error

### ISSUE THREAD

**Issue by gsabo** [joommf/help#9]
I have used Anaconda3-2020.02-Linux-x86_64.sh, the Linux Python 3.7 64-Bit (x86) installer, that is currently at [1].

This to report  the following error from the terminal command: 
python3 -c "import oommfc; oommfc.test()"

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/oommfc/__init__.py", line 3, in <module>
    import oommfc.oommf
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/oommfc/oommf/__init__.py", line 1, in <module>
    from .oommf import OOMMFRunner, TclOOMMFRunner, ExeOOMMFRunner, \
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/oommfc/oommf/oommf.py", line 11, in <module>
    import micromagneticmodel as mm
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/micromagneticmodel/__init__.py", line 5, in <module>
    import micromagneticmodel.examples
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/micromagneticmodel/examples/__init__.py", line 1, in <module>
    from .examples import macrospin
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/micromagneticmodel/examples/examples.py", line 1, in <module>
    import discretisedfield as df
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/discretisedfield/__init__.py", line 12, in <module>
    __dependencies__ = pkg_resources.require(__name__)
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tornado 6.0.1 (/home/username/.local/lib/python3.6/site-packages), Requirement.parse('tornado!=6.0.0,!=6.0.1,!=6.0.2'), {'jupyterlab'})

I'm able to workaround the error by using:

conda install tornado=6.0.2

However, it is failing with the above error with tornado 6.0.4 that gets installed using "conda install ubermag -c conda-forge".

[1] https://www.anaconda.com/products/individual

**Comment by gsabo** [comment]
Moved from joommf/help to ubermag/help:

https://github.com/ubermag/help/issues/69
